version: "3.7"
services:
  orthanc:
    build: orthanc
    depends_on: [ orthanc-index ]
    restart: unless-stopped
    ports: [ "4242:4242", "8042:8042" ]
    volumes: [ "orthanc-storage:/var/lib/orthanc/db:Z" ]
    environment:
      ORTHANC_WEB_VIEWER_PLUGIN_ENABLED: "true"
      STONE_WEB_VIEWER_PLUGIN_ENABLED=true: "true"
      DICOM_WEB_PLUGIN_ENABLED: "true"
      OSIMIS_WEB_VIEWER1_PLUGIN_ENABLED: "true"
      VERBOSE_STARTUP: "true"
      ORTHANC__REGISTERED_USERS: |
        {"demo": "demo"}
      ORTHANC__EXTRA_MAIN_DICOM_TAGS: |+
        {
          "Instance" : [
              "Rows",
              "Columns",
              "ImageType",
              "SOPClassUID",
              "ContentDate",
              "ContentTime",
              "FrameOfReferenceUID",
              "PixelSpacing",
              "SpecificCharacterSet",
              "BitsAllocated",
              "BitsStored",

              "RescaleSlope",
              "RescaleIntercept",
              "SliceThickness",
              "WindowCenter",
              "WindowWidth",
              "PhotometricInterpretation",
              "PixelRepresentation"
          ],
          "Series" : [
              "TimezoneOffsetFromUTC",
              "PerformedProcedureStepStartDate",
              "PerformedProcedureStepStartTime",
              "RequestAttributesSequence"
          ],
          "Study": [
              "TimezoneOffsetFromUTC"
          ],
          "Patient": []
          }
          
  orthanc-index:
    image: postgres
    restart: unless-stopped
    ports: [ "5442:5432" ]
    volumes: [ "orthanc-index:/var/lib/postgresql/data:Z" ]
    environment:
      POSTGRES_PASSWORD: "postgres"

volumes:
  orthanc-storage:
  orthanc-index:
