version: "3.7"
services:
  orthanc:
    image: osimis/orthanc
    ports:
      - 4242:4242
      - 8042:8042
    environment:
      ORTHANC_WEB_VIEWER_PLUGIN_ENABLED: "true"
      STONE_WEB_VIEWER_PLUGIN_ENABLED=true: "true"
      DICOM_WEB_PLUGIN_ENABLED: "true"
      OSIMIS_WEB_VIEWER1_PLUGIN_ENABLED: "true"
      VERBOSE_STARTUP: "true"
      ORTHANC__REGISTERED_USERS: |
        {"demo": "demo"}
    # network_mode: host
    volumes:
      # - /orthanc.json:/etc/orthanc/orthanc.json:ro
      - ./tmp/orthanc-db/:/var/lib/orthanc/db/
